[build]
builder = "NIXPACKS"

[build.env]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
NIXPACKS_APT_PKGS = "chromium-browser ffmpeg"

[deploy]
startCommand = "node src/daily.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "cutthebs-daily"

[services.cron]
schedule = "0 17 * * *"
command = "node src/daily.js"
